
   
version: "3"

services:
  mysql:
    image: mysql:8.0
    networks:
      - network   
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: cmpe172
    volumes:
    - "./init.sql:/docker-entrypoint-initdb.d/1.sql"

    restart: always

  users:
    #image: rheadash/spring-users:v1
    image: qnguyen3411/airbnb-backend:latest
    depends_on:
    - mysql    
    volumes:
      - /tmp:/tmp
    networks:
      - network   
    ports:
      - 8081:8080
    environment:
      MYSQL_HOST: mysql
    restart: always 

  property:
    image: qnguyen3411/airbnb-property:latest
    depends_on:
    - mysql    
    volumes:
      - /tmp:/tmp
    networks:
      - network   
    ports:
      - 8082:8080
    environment:
      MYSQL_HOST: mysql
    restart: always 
  
  payments:
    image: qnguyen3411/airbnb-payments:latest
    depends_on:
    - property    
    volumes:
      - /tmp:/tmp
    networks:
      - network   
    ports:
      - 8083:8080
    environment:
      MYSQL_HOST: mysql
      PROPERTY_ENDPOINT: http://localhost:8082/property/
    restart: always 
  

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge